### PR TITLE
ci: migrate to github actions

### PR DESCRIPTION
**Pull request by varl**
To migrate to GitHub Actions and our library workflows a few changes are
needed:

First up, removing the .travis.yml and adding in the
.github/workflows/dhis2-verify-lib.yml.

The lint job is left commented out, as there are 600+ linting errors
reported (all autofixable it seems), but fixing the lint errors should
be in a different commit, as this needs to be backported and is designed
to be easy to move to other branches.

The main entrypoint in package.json was pointing to a directory that
doesn't exist, so that has been updated to build/index.js.

When moving to the d2-utils-release script, we will no longer publish
this as a flat package, so this is potentially a breaking change. I
think that it worked because the lib was compiled into build/index.js,
and then since the main entrypoint in package.json did not exist, the
file-loader fell back to loading the index.js from the package, which
happened to exist in the root folder because of the flatpack structure
in the released artifact.

This should "just work" with the correct entry-point even if we no
longer release the flat package.

Old version of node-sass has been bumped to 4.13.1 which is close to the
previous to not have any breaking changes, but supports node versions >=
10.

Fix: https://jira.dhis2.org/browse/TECH-512

### CODE REVIEW

**Comment by varl** [comment]
This has the consequence that, in terms of release branches, we need to use:

- `33.x` instead of `2.33`
- `32.x` instead of `2.32`

**Comment by varl** [comment]
If this is OK I will backport this migration to 2.32 and 2.33 so those versions can be released as well.

**Review by turban — APPROVED** [review]
LGTM. 

Will this change how I create a new version for this repo? Previously I've used: 
```
git tag version
git push --tags
```

Will it now be auto-published like @dhis2/maps-gl?

**Comment by varl** [comment]
Yes, that would change to the same system as `@dhis2/maps-gl`.

Another one would be that to release a backport on 2.33, we need to merge to `33.x` instead of `2.33`.

**Pull request merged**
